AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repositories for the Cattlepoint stack

Resources:
  CattlepointDatabaseRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: cattlepoint-database

  CattlepointBackendRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: cattlepoint-backend

  CattlepointFrontendRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: cattlepoint-frontend

Outputs:
  DatabaseRepositoryUri:
    Description: URI of the cattlepoint-database repository
    Value: !GetAtt CattlepointDatabaseRepo.RepositoryUri

  BackendRepositoryUri:
    Description: URI of the cattlepoint-backend repository
    Value: !GetAtt CattlepointBackendRepo.RepositoryUri

  FrontendRepositoryUri:
    Description: URI of the cattlepoint-frontend repository
    Value: !GetAtt CattlepointFrontendRepo.RepositoryUri
